name: pyrin_app
description: "Pyrin native wallet application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  qr_flutter: ^4.1.0
  provider: ^6.1.2
  mobile_scanner: ^5.1.1
  intl: ^0.19.0
  ffi: ^2.1.3
  pyrin:
    path: ../../pyrin-public/sdk/flutter/dart
#    path: ../../../../Downloads/rust-dart-bindings/dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/icons/scan.svg
   - assets/icons/notification.svg
   - assets/icons/swap.svg
   - assets/icons/primary-swap.svg
   - assets/icons/send.svg
   - assets/icons/receive.svg
   - assets/icons/arrow-left.svg
   - assets/icons/arrow-right.svg
   - assets/icons/close.svg
   - assets/icons/search.svg
   - assets/icons/avatar.svg
   - assets/icons/diamond.svg
   - assets/icons/add.svg
   - assets/icons/copy.svg
   - assets/icons/menu.svg
   - assets/icons/home.svg
   - assets/icons/market.svg
   - assets/icons/assets.svg
   - assets/icons/task.svg
   - assets/icons/setting.svg
   - assets/icons/sun.svg
   - assets/icons/key.svg
   - assets/icons/notification.svg
   - assets/icons/message.svg
   - assets/icons/life-buoy.svg
   - assets/icons/logout.svg
   - assets/icons/lovely.svg
   - assets/icons/eye.svg
   - assets/icons/arrow-small-right.svg
   - assets/icons/arrow-right-short.svg
   - assets/icons/arrow-down.svg
   - assets/icons/switch.svg
   - assets/icons/char.svg
   - assets/home_bg_circles.svg
   - assets/home_list_divider.svg
   - assets/home_nav_bg.svg
   - assets/pyrin-coin.svg
   - assets/tick-circle.svg
   - assets/close-circle.svg
   - assets/biometric.svg
   - assets/pyrin.svg
   - assets/welcome_banner_1.png
   - assets/welcome_banner_2.png
   - assets/welcome_banner_3.png
   - assets/welcome_banner_4.png
   - assets/pyrin_flutter_bg.wasm

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
